### ISSUE TITLE
Simpler solution 

### ISSUE THREAD

**Issue by malhal** [thoughtbot/CombineViewModel#24]
“ The problem with objectWillChange outside of SwiftUI is that there's no built-in way of achieving (2) — being notified that an object will change is not the same as knowing that it did change and it’s time to update the view.”

You can simply use the debounce operator on the willChange publisher and now it’s becomes didChange. And multiple changes to the object result in only one update. The same way multiple changes to objects in SwiftUI result in only one call to body.

And by the way, View model pattern is not compatible with SwiftUI. SwiftUI View structs are already the model for the UIViews that are eventually shown on screen. You should use @State and @Binding to make the structs behave like objects. One value in a @State, if you have 2 values make a struct to hold them and use @State, if you need to use Combine or implement a delegate then use a @StateObject and store the struct that holds the 2 or more values in an @Published var. Typically this kind of ObservableObject is use for loading or fetching where the data needs to be tied to the view lifecycle.

**Comment by SF-Simon** [comment]
Hello, is the corresponding demonstration code? I am very interested in this idea, if you can, please provide a reliable code, thank you.

@malhal

**Comment by malhal** [comment]
Just watch this https://developer.apple.com/videos/play/wwdc2020/10040/

**Comment by sharplet** [comment]
> You can simply use the debounce operator on the willChange publisher and now it’s becomes didChange.

If you're interested, I'd be happy to review a PR with a test that demonstrates the approaches are equivalent.

> The same way multiple changes to objects in SwiftUI result in only one call to body.

Unfortunately, neither approach is actually equivalent to what SwiftUI does internally. SwiftUI controls the render loop, and is able to ensure that the views are re-evaluated before the next "tick" rendering the UI. This results in smoother animations than what we're able to currently achieve with either the dispatch source approach implemented here or a debouncing approach, which always appear to be scheduled during the _following_ tick.

> And by the way, View model pattern is not compatible with SwiftUI. SwiftUI View structs are already the model for the UIViews that are eventually shown on screen....Typically this kind of ObservableObject is use for loading or fetching where the data needs to be tied to the view lifecycle.

The term "view model" used by this project is used intentionally to model those long-running operations. Other design patterns have called these objects "controllers" or "presenters", but the concept is the same.
